### ISSUE TITLE
DELETE "https:://" on the result page

### ISSUE THREAD

**Issue by shouya** [path/posthere.io#3]
hi,

there is an extra colon on the result page that prevent copying for cURL.

demo: https://posthere.io/22f7-4ad6-b39f
screenshot: ![image](https://cloud.githubusercontent.com/assets/526598/8394177/9eea9598-1cf9-11e5-82b6-f8942fad764d.png)

**Comment by belucid** [comment]
Thanks for the report! Fixed the issue here:

https://github.com/SnootyMonkey/posthere.io/commit/e09508007c44987e5478366d69958ac86612c3b0

Enjoy!
